//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studio365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarriageOrder
    {
        public int sno { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustomerDetails { get; set; }
        public string OrderDetails { get; set; }
        public Nullable<int> AdvanceAmount { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public Nullable<int> Total { get; set; }
        public string EmployeeID { get; set; }
    }
}
