//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studio365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public int Sno { get; set; }
        public string ProductTypes { get; set; }
        public string ProductSubTypes { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> GST { get; set; }
        public string Status { get; set; }
    }
}
