//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studio365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Sno { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustomerMobile { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> GST { get; set; }
        public string Orders { get; set; }
    }
}
