//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studio365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageConfiguration
    {
        public int sno { get; set; }
        public string PackageName { get; set; }
        public string PackageDetails { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string EmployeeID { get; set; }
    }
}
