//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studio365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        public int Sno { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Userrole { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Password { get; set; }
    }
}
